# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1a6b44dc2688b7a90f06a245ad43721eead7d29282fbe32df876df7bd9c0399a8a584060e032ffadf124458c34e4d369a4377441fd9f62acec101c78f2da81

test:
  secret_key_base: eb4c81a15d5ffff811ca20e0006fab38f0b37d5d4270effd601c15252ad09a0ec7d839160e06d267a994a1985710bea3bc8cec3042a51af0b6135141926ba457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
